[tool.poetry]
name = "cyberattack-detection"
version = "0.1.0"
description = ""
authors = ["gabrielonishi <gabriel.onishi@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
